# Generated by Django 5.2 on 2025-04-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('till', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
